package net.easipay.cbp.model;


import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;


/**
 * UcOperator generated by hbm2java
 */
@Entity
@Table(name = "UC_OPERATOR", schema = "CBP_UC")
public class UcOperator implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	@Size(min=1,max=32,message="{filed.length.error.between}")
	private String loginName;
	@Size(max=32,message="{filed.length.error}")
	private String loginNameCh;
	private String password;
	@Pattern(regexp = "^[1]+\\d{10}", message="{filed.phone.error}")
	private String mobile;
	@Pattern(regexp = "^\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*$", message="{filed.email.error}")
	private String email;
	private Long roleId;
	private String orgId;
	private Long createUserId;
	private Date createTime;
	private Long updateUserId;
	private Date updateTime;
	private String userType;
	private String status;
	@Size(max=256,message="{filed.length.error}")
	private String memo;

	public UcOperator() {
	}

	public UcOperator(Long id) {
		this.id = id;
	}

	public UcOperator(Long id, String loginName, String loginNameCh,
			String password, String mobile, String email, Long roleId,
			String orgId, Long createUserId, Date createTime,
			Long updateUserId, Date updateTime, String userType,
			String status, String memo) {
		this.id = id;
		this.loginName = loginName;
		this.loginNameCh = loginNameCh;
		this.password = password;
		this.mobile = mobile;
		this.email = email;
		this.roleId = roleId;
		this.orgId = orgId;
		this.createUserId = createUserId;
		this.createTime = createTime;
		this.updateUserId = updateUserId;
		this.updateTime = updateTime;
		this.userType = userType;
		this.status = status;
		this.memo = memo;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getLoginNameCh() {
		return loginNameCh;
	}

	public void setLoginNameCh(String loginNameCh) {
		this.loginNameCh = loginNameCh;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Long getRoleId() {
		return roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public Long getCreateUserId() {
		return createUserId;
	}

	public void setCreateUserId(Long createUserId) {
		this.createUserId = createUserId;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getUpdateUserId() {
		return updateUserId;
	}

	public void setUpdateUserId(Long updateUserId) {
		this.updateUserId = updateUserId;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
