package net.easipay.cbp.model;



import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * UcRole generated by hbm2java
 */
@Entity
@Table(name = "uc_role_resource", schema = "CBP_UC")
public class UcRoleResource implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long roleId;
	private Long resourceId;
	
	public Long getRoleId() {
		return roleId;
	}
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}
	public Long getResourceId() {
		return resourceId;
	}
	public void setResourceId(Long resourceId) {
		this.resourceId = resourceId;
	}

   
	
}
