package net.easipay.cbp.model;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Length;

/**
 * UcRole generated by hbm2java
 */

public class UcRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6126997690277310412L;

	private Long id;
	
	@Size(max=8,message="{ucRole.length.error}")
//	@Pattern(regexp="\\S{2}", message="{ucRole.roleCode.error}")
//	@Length(max=8)
	private String roleCode;
	@Size(max=32,message="{ucRole.length.error}")
//	@Length(max=8)
	private String roleName;
	private String status;
	@Size(max=256,message="{ucRole.length.error}")
//	@Length(max=8)
	private String description;
	private Long createUserId;
	private Date createTime;
	private Long updateUserId;
	private Date updateTime;
	private String memo;

	public UcRole() {
	}

	public UcRole(Long id) {
		this.id = id;
	}

	public UcRole(Long id, String roleCode, String roleName,
			String status, String description, Long createUserId,
			Date createTime, Long updateUserId, Date updateTime,
			String memo) {
		this.id = id;
		this.roleCode = roleCode;
		this.roleName = roleName;
		this.status = status;
		this.description = description;
		this.createUserId = createUserId;
		this.createTime = createTime;
		this.updateUserId = updateUserId;
		this.updateTime = updateTime;
		this.memo = memo;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Long createUserId) {
		this.createUserId = createUserId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(Long updateUserId) {
		this.updateUserId = updateUserId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
