package net.easipay.cbp.model;

import javax.persistence.Entity;


/**
 * UcRole generated by hbm2java
 */
@Entity
public class BussTypeGroup implements java.io.Serializable {

	private String bussType;
	private String bussTypeName;
	private String bussTypeCount;
	private String bussTypeSum;
	private String bussTypeDate;
	
	
	/**
	 * @return the bussTypeSum
	 */
	public String getBussTypeSum() {
		return bussTypeSum;
	}
	/**
	 * @param bussTypeSum the bussTypeSum to set
	 */
	public void setBussTypeSum(String bussTypeSum) {
		this.bussTypeSum = bussTypeSum;
	}
	/**
	 * @return the bussTypeDate
	 */
	public String getBussTypeDate() {
		return bussTypeDate;
	}
	/**
	 * @param bussTypeDate the bussTypeDate to set
	 */
	public void setBussTypeDate(String bussTypeDate) {
		this.bussTypeDate = bussTypeDate;
	}
	/**
	 * @return the bussType
	 */
	public String getBussType() {
		return bussType;
	}
	/**
	 * @param bussType the bussType to set
	 */
	public void setBussType(String bussType) {
		this.bussType = bussType;
	}
	/**
	 * @return the bussTypeName
	 */
	public String getBussTypeName() {
		return bussTypeName;
	}
	/**
	 * @param bussTypeName the bussTypeName to set
	 */
	public void setBussTypeName(String bussTypeName) {
		this.bussTypeName = bussTypeName;
	}
	/**
	 * @return the bussTypeCount
	 */
	public String getBussTypeCount() {
		return bussTypeCount;
	}
	/**
	 * @param bussTypeCount the bussTypeCount to set
	 */
	public void setBussTypeCount(String bussTypeCount) {
		this.bussTypeCount = bussTypeCount;
	}
	/**
	 * @return the bussTypeSum
	 */
	public String getbussTypeSum() {
		return bussTypeSum;
	}
	/**
	 * @param bussTypeSum the bussTypeSum to set
	 */
	public void setbussTypeSum(String bussTypeSum) {
		this.bussTypeSum = bussTypeSum;
	}

	
	
	
	
	  
	  
	
   
	
}
