package net.easipay.cbp.model;

// Generated 2015-7-2 9:35:55 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FIN_STAT_BANK generated by hbm2java
 */
@Entity
@Table(name = "FIN_STAT_BANK", schema = "SAC_SYN")
public class FinStatBank implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3247099678432951122L;
	private Long statBankId;
	private String codeId;
	private BigDecimal openBal;
	private BigDecimal closeBal;
	private BigDecimal fDebit;
	private BigDecimal fCredit;
	private BigDecimal amount;
	private long direction;
	private Date statTime;
	public Long getStatBankId() {
		return statBankId;
	}
	public void setStatBankId(Long statBankId) {
		this.statBankId = statBankId;
	}
	public String getCodeId() {
		return codeId;
	}
	public void setCodeId(String codeId) {
		this.codeId = codeId;
	}
	public BigDecimal getOpenBal() {
		return openBal;
	}
	public void setOpenBal(BigDecimal openBal) {
		this.openBal = openBal;
	}
	public BigDecimal getCloseBal() {
		return closeBal;
	}
	public void setCloseBal(BigDecimal closeBal) {
		this.closeBal = closeBal;
	}
	public BigDecimal getfDebit() {
		return fDebit;
	}
	public void setfDebit(BigDecimal fDebit) {
		this.fDebit = fDebit;
	}
	public BigDecimal getfCredit() {
		return fCredit;
	}
	public void setfCredit(BigDecimal fCredit) {
		this.fCredit = fCredit;
	}
	public BigDecimal getAmount() {
		return amount;
	}
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	public long getDirection() {
		return direction;
	}
	public void setDirection(long direction) {
		this.direction = direction;
	}
	public Date getStatTime() {
		return statTime;
	}
	public void setStatTime(Date statTime) {
		this.statTime = statTime;
	}
	


}
