package net.easipay.cbp.model;

// Generated 2015-7-2 9:35:55 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;


/**
 * FIN_STAT_BANK generated by hbm2java
 */
public class FinStatBankForm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3247099678432951122L;
	
	private String cusId;
	private String currency;
	private Date startDate;
	private Date endDate;
	private Long statBankId;
	private String codeId;
	private BigDecimal openBal;
	private BigDecimal closeBal;
	private BigDecimal fDebit;
	private BigDecimal fCredit;
	private BigDecimal amount;
	private long direction;
	private Date statTime;
	private String sacBankName;
	private String bankAcc;
	private BigDecimal diffSum;
	private BigDecimal dealSum;
	public String getCusId() {
		return cusId;
	}
	public void setCusId(String cusId) {
		this.cusId = cusId;
	}
	public String getCurrency() {
		return currency;
	}
	public void setCurrency(String currency) {
		this.currency = currency;
	}
	public Date getStartDate() {
		return startDate;
	}
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	public Date getEndDate() {
		return endDate;
	}
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	public Long getStatBankId() {
		return statBankId;
	}
	public void setStatBankId(Long statBankId) {
		this.statBankId = statBankId;
	}
	public String getCodeId() {
		return codeId;
	}
	public void setCodeId(String codeId) {
		this.codeId = codeId;
	}
	public BigDecimal getOpenBal() {
		return openBal;
	}
	public void setOpenBal(BigDecimal openBal) {
		this.openBal = openBal;
	}
	public BigDecimal getCloseBal() {
		return closeBal;
	}
	public void setCloseBal(BigDecimal closeBal) {
		this.closeBal = closeBal;
	}
	public BigDecimal getfDebit() {
		return fDebit;
	}
	public void setfDebit(BigDecimal fDebit) {
		this.fDebit = fDebit;
	}
	public BigDecimal getfCredit() {
		return fCredit;
	}
	public void setfCredit(BigDecimal fCredit) {
		this.fCredit = fCredit;
	}
	public BigDecimal getAmount() {
		return amount;
	}
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	public long getDirection() {
		return direction;
	}
	public void setDirection(long direction) {
		this.direction = direction;
	}
	public Date getStatTime() {
		return statTime;
	}
	public void setStatTime(Date statTime) {
		this.statTime = statTime;
	}
	public String getSacBankName() {
		return sacBankName;
	}
	public void setSacBankName(String sacBankName) {
		this.sacBankName = sacBankName;
	}
	public String getBankAcc() {
		return bankAcc;
	}
	public void setBankAcc(String bankAcc) {
		this.bankAcc = bankAcc;
	}
	public BigDecimal getDiffSum() {
		return diffSum;
	}
	public void setDiffSum(BigDecimal diffSum) {
		this.diffSum = diffSum;
	}
	public BigDecimal getDealSum() {
		return dealSum;
	}
	public void setDealSum(BigDecimal dealSum) {
		this.dealSum = dealSum;
	}
	
	
	
	


}
