package net.easipay.cbp.model;

// Generated 2015-7-6 15:57:25 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SacCusSettlemen generated by hbm2java
 */
@Entity
@Table(name = "SAC_CUS_SETTLEMENT", schema = "SAC_SYN")
public class SacCusSettlement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1119637615832924651L;
	private Long id;
	private String cusNo;
	private String cusName;
	private String sacDate;
	private Integer totalNum;
	private BigDecimal totalAmount;
	private String currencyType;
	private BigDecimal fees;
	private BigDecimal sacAmount;
	private Date createTime;
	private String finSign;
	private String setBatchNo;
	private String draccNo;
	private String draccName;
	private String draccNodeCode;
	private String draccBankName;
	private String memo;
	private String transferStatus;
	private String trxType;
	private String bussType;
	private String sacSign;
	
	

	public SacCusSettlement() {
	}

	public SacCusSettlement(Long id, String cusNo, String cusName) {
		this.id = id;
		this.cusNo = cusNo;
		this.cusName = cusName;
	}

	public SacCusSettlement(Long id, String cusNo, String cusName,
			String sacDate, Integer totalNum, BigDecimal totalAmount,
			BigDecimal fees, BigDecimal sacAmount, Date createTime,
			String finSign, String draccNo, String draccName,
			String draccNodeCode, String draccBankName, String memo) {
		this.id = id;
		this.cusNo = cusNo;
		this.cusName = cusName;
		this.sacDate = sacDate;
		this.totalNum = totalNum;
		this.totalAmount = totalAmount;
		this.fees = fees;
		this.sacAmount = sacAmount;
		this.createTime = createTime;
		this.finSign = finSign;
		this.draccNo = draccNo;
		this.draccName = draccName;
		this.draccNodeCode = draccNodeCode;
		this.draccBankName = draccBankName;
		this.memo = memo;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CUS_NO", nullable = false, length = 8)
	public String getCusNo() {
		return this.cusNo;
	}

	public void setCusNo(String cusNo) {
		this.cusNo = cusNo;
	}

	@Column(name = "CUS_NAME", nullable = false, length = 50)
	public String getCusName() {
		return this.cusName;
	}

	public void setCusName(String cusName) {
		this.cusName = cusName;
	}

	@Column(name = "SAC_DATE", length = 11)
	public String getSacDate() {
		return this.sacDate;
	}

	public void setSacDate(String sacDate) {
		this.sacDate = sacDate;
	}

	@Column(name = "TOTAL_NUM", precision = 9, scale = 0)
	public Integer getTotalNum() {
		return this.totalNum;
	}

	public void setTotalNum(Integer totalNum) {
		this.totalNum = totalNum;
	}

	@Column(name = "TOTAL_AMOUNT")
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "FEES")
	public BigDecimal getFees() {
		return this.fees;
	}

	public void setFees(BigDecimal fees) {
		this.fees = fees;
	}

	@Column(name = "SAC_AMOUNT")
	public BigDecimal getSacAmount() {
		return this.sacAmount;
	}

	public void setSacAmount(BigDecimal sacAmount) {
		this.sacAmount = sacAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 11)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "FIN_SIGN", length = 2)
	public String getFinSign() {
		return this.finSign;
	}

	public void setFinSign(String finSign) {
		this.finSign = finSign;
	}

	@Column(name = "DRACC_NO", length = 50)
	public String getDraccNo() {
		return this.draccNo;
	}

	public void setDraccNo(String draccNo) {
		this.draccNo = draccNo;
	}

	@Column(name = "DRACC_NAME", length = 100)
	public String getDraccName() {
		return this.draccName;
	}

	public void setDraccName(String draccName) {
		this.draccName = draccName;
	}

	@Column(name = "DRACC_NODE_CODE", length = 8)
	public String getDraccNodeCode() {
		return this.draccNodeCode;
	}

	public void setDraccNodeCode(String draccNodeCode) {
		this.draccNodeCode = draccNodeCode;
	}

	@Column(name = "DRACC_BANK_NAME", length = 40)
	public String getDraccBankName() {
		return this.draccBankName;
	}

	public void setDraccBankName(String draccBankName) {
		this.draccBankName = draccBankName;
	}

	@Column(name = "MEMO", length = 100)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getCurrencyType() {
		return currencyType;
	}

	public void setCurrencyType(String currencyType) {
		this.currencyType = currencyType;
	}

	public String getTransferStatus() {
		return transferStatus;
	}

	public void setTransferStatus(String transferStatus) {
		this.transferStatus = transferStatus;
	}

	public String getSetBatchNo() {
		return setBatchNo;
	}

	public void setSetBatchNo(String setBatchNo) {
		this.setBatchNo = setBatchNo;
	}

	public String getTrxType() {
		return trxType;
	}

	public void setTrxType(String trxType) {
		this.trxType = trxType;
	}

	public String getBussType() {
		return bussType;
	}

	public void setBussType(String bussType) {
		this.bussType = bussType;
	}

	public String getSacSign() {
		return sacSign;
	}

	public void setSacSign(String sacSign) {
		this.sacSign = sacSign;
	}
	
	

}
