package net.easipay.cbp.model;

// Generated 2015-7-6 15:57:25 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * SacChnSettlement generated by hbm2java
 */
@Entity
@Table(name = "SAC_CHN_SETTLEMENT", schema = "SAC_SYN")
public class SacChnSettlement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5280004874365180549L;
	private Long id;
	private String bankNodeCode;
	private String sacBankName;
	private String accountNumber;
	private String sacDate;
	private String trxDate;
	private String transDate;
	private String type;
	private Integer totalNum;
	private BigDecimal totalSum;
	private BigDecimal trxCost;
	private BigDecimal receiveTotSum;
	private BigDecimal realTotAmount;
	private String currencyType;
	private String finSign;
	private String chnBatchNo;
	private Date createTime;
	private Date updateTime;
	private String memo;
	private String startSacDate;
	private String endSacDate;

	public SacChnSettlement() {
		
	}

	public SacChnSettlement(Long id, String bankNodeCode, String sacBankName)
	{
		this.id = id;
		this.bankNodeCode = bankNodeCode;
		this.sacBankName = sacBankName;
	}

	public SacChnSettlement(Long id, String bankNodeCode, String sacBankName, String accountNumber, String sacDate, String trxDate, String transDate, String type, Integer totalNum, BigDecimal totalSum, BigDecimal trxCost, BigDecimal receiveTotSum, BigDecimal realTotAmount, String currencyType,
			String finSign, String chnBatchNo, Date createTime, Date updateTime, String memo)
	{
		this.id = id;
		this.bankNodeCode = bankNodeCode;
		this.sacBankName = sacBankName;
		this.accountNumber = accountNumber;
		this.sacDate = sacDate;
		this.trxDate = trxDate;
		this.transDate = transDate;
		this.type = type;
		this.totalNum = totalNum;
		this.totalSum = totalSum;
		this.trxCost = trxCost;
		this.receiveTotSum = receiveTotSum;
		this.realTotAmount = realTotAmount;
		this.currencyType = currencyType;
		this.finSign = finSign;
		this.chnBatchNo = chnBatchNo;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.memo = memo;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "BANK_NODE_CODE", nullable = false, length = 8)
	public String getBankNodeCode()
	{
		return bankNodeCode;
	}

	public void setBankNodeCode(String bankNodeCode)
	{
		this.bankNodeCode = bankNodeCode;
	}

	@Column(name = "SAC_BANK_NAME", nullable = false, length = 50)
	public String getSacBankName()
	{
		return sacBankName;
	}

	public void setSacBankName(String sacBankName)
	{
		this.sacBankName = sacBankName;
	}

	@Column(name = "ACCOUNT_NUMBER", length = 50)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "SAC_DATE", length = 50)
	public String getSacDate() {
		return this.sacDate;
	}

	public void setSacDate(String sacDate) {
		this.sacDate = sacDate;
	}

	@Column(name = "TRX_DATE", length = 50)
	public String getTrxDate() {
		return this.trxDate;
	}

	public void setTrxDate(String trxDate) {
		this.trxDate = trxDate;
	}

	@Column(name = "TYPE", length = 2)
	public String getType() {
		return this.type;
	}

	public String getTransDate() {
		return transDate;
	}

	public void setTransDate(String transDate) {
		this.transDate = transDate;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "TOTAL_NUM", precision = 9, scale = 0)
	public Integer getTotalNum() {
		return this.totalNum;
	}

	public void setTotalNum(Integer totalNum) {
		this.totalNum = totalNum;
	}

	@Column(name = "TOTAL_SUM")
	public BigDecimal getTotalSum() {
		return this.totalSum;
	}

	public void setTotalSum(BigDecimal totalSum) {
		this.totalSum = totalSum;
	}

	@Column(name = "TRX_COST")
	public BigDecimal getTrxCost() {
		return this.trxCost;
	}

	public void setTrxCost(BigDecimal trxCost) {
		this.trxCost = trxCost;
	}

	@Column(name = "RECEIVE_TOT_SUM")
	public BigDecimal getReceiveTotSum() {
		return this.receiveTotSum;
	}

	public void setReceiveTotSum(BigDecimal receiveTotSum) {
		this.receiveTotSum = receiveTotSum;
	}

	@Column(name = "REAL_TOT_AMOUNT")
	public BigDecimal getRealTotAmount() {
		return this.realTotAmount;
	}

	public void setRealTotAmount(BigDecimal realTotAmount) {
		this.realTotAmount = realTotAmount;
	}

	@Column(name = "CURRENCY_TYPE", length = 4)
	public String getCurrencyType() {
		return this.currencyType;
	}

	public void setCurrencyType(String currencyType) {
		this.currencyType = currencyType;
	}

	@Column(name = "FIN_SIGN", length = 2)
	public String getFinSign() {
		return this.finSign;
	}

	public void setFinSign(String finSign) {
		this.finSign = finSign;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 11)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 11)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "MEMO", length = 100)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getChnBatchNo() {
		return chnBatchNo;
	}

	public void setChnBatchNo(String chnBatchNo) {
		this.chnBatchNo = chnBatchNo;
	}

	public String getStartSacDate() {
		return startSacDate;
	}

	public void setStartSacDate(String startSacDate) {
		this.startSacDate = startSacDate;
	}

	public String getEndSacDate() {
		return endSacDate;
	}

	public void setEndSacDate(String endSacDate) {
		this.endSacDate = endSacDate;
	}
	

	
}
