package net.easipay.cbp.model;

import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * SacOtrxInfo generated by hbm2java
 */
@Entity
@Table(name = "SAC_CHECK_INFO", schema = "SAC_SYN")
public class SacCheckInfo implements java.io.Serializable {

	/**
	 * 
	 */
             
	private static final long serialVersionUID = -2922429917705296479L;
	private Long id;
	private String trxType;
	private String checkStatus;
	private String operator;
	private Date operatorTime;
	private String digst;	
	private Date updateTime;
	private Date createTime;	
	private String memo;
	private String startDate;
	private String endDate;
	
	public SacCheckInfo(){};
	
	public SacCheckInfo(Long id, String trxType, String checkStatus,
			String operator, Date operatorTime, String digst, Date updateTime,
			Date createTime, String memo) {
		super();
		this.id = id;
		this.trxType = trxType;
		this.checkStatus = checkStatus;
		this.operator = operator;
		this.operatorTime = operatorTime;
		this.digst = digst;
		this.updateTime = updateTime;
		this.createTime = createTime;
		this.memo = memo;
	}
	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}
	/**
	 * @return the trxType
	 */
	public String getTrxType() {
		return trxType;
	}
	/**
	 * @param trxType the trxType to set
	 */
	public void setTrxType(String trxType) {
		this.trxType = trxType;
	}
	/**
	 * @return the checkStatus
	 */
	public String getCheckStatus() {
		return checkStatus;
	}
	/**
	 * @param checkStatus the checkStatus to set
	 */
	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}
	/**
	 * @return the operator
	 */
	public String getOperator() {
		return operator;
	}
	/**
	 * @param operator the operator to set
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}
	/**
	 * @return the operatorTime
	 */
	public Date getOperatorTime() {
		return operatorTime;
	}
	/**
	 * @param operatorTime the operatorTime to set
	 */
	public void setOperatorTime(Date operatorTime) {
		this.operatorTime = operatorTime;
	}
	/**
	 * @return the digst
	 */
	public String getDigst() {
		return digst;
	}
	/**
	 * @param digst the digst to set
	 */
	public void setDigst(String digst) {
		this.digst = digst;
	}
	/**
	 * @return the updateTime
	 */
	public Date getUpdateTime() {
		return updateTime;
	}
	/**
	 * @param updateTime the updateTime to set
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return createTime;
	}
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	/**
	 * @return the memo
	 */
	public String getMemo() {
		return memo;
	}
	/**
	 * @param memo the memo to set
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}
	
	
		
}
