package net.easipay.cbp.model;

// Generated 2015-7-6 15:57:25 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SacRefund generated by hbm2java
 */
@Entity
@Table(name = "SAC_REFUND", schema = "SAC_SYN")
public class SacRefund implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1227239078951621900L;
	private Long id;
	private String rtrxSerialNo;
	private Date refundTime;
	private String otrxSerialNo;
	private Date otrxDate;
	private String opayChnNo;
	private String opayChnName;
	private String omerBillNo;
	private BigDecimal otrxAmount;
	private BigDecimal refundAmount;
	private String refundStatus;
	private Date createTime;
	private String memo;
	private String confirmUser;
	private String confirmStatus;
	private Date confirmTime;
	private String trxErrDealType;

	public SacRefund() {
	}

	public SacRefund(Long id, String rtrxSerialNo, Date refundTime) {
		this.id = id;
		this.rtrxSerialNo = rtrxSerialNo;
		this.refundTime = refundTime;
	}

	public SacRefund(Long id, String rtrxSerialNo, Date refundTime,
			String otrxSerialNo, Date otrxDate, String opayChnNo,
			String opayChnName, String omerBillNo, BigDecimal otrxAmount,
			BigDecimal refundAmount, String refundStatus, Date createTime,
			String memo, String confirmUser, String confirmStatus,
			Date confirmTime) {
		this.id = id;
		this.rtrxSerialNo = rtrxSerialNo;
		this.refundTime = refundTime;
		this.otrxSerialNo = otrxSerialNo;
		this.otrxDate = otrxDate;
		this.opayChnNo = opayChnNo;
		this.opayChnName = opayChnName;
		this.omerBillNo = omerBillNo;
		this.otrxAmount = otrxAmount;
		this.refundAmount = refundAmount;
		this.refundStatus = refundStatus;
		this.createTime = createTime;
		this.memo = memo;
		this.confirmUser = confirmUser;
		this.confirmStatus = confirmStatus;
		this.confirmTime = confirmTime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "RTRX_SERIAL_NO", nullable = false, length = 30)
	public String getRtrxSerialNo() {
		return this.rtrxSerialNo;
	}

	public void setRtrxSerialNo(String rtrxSerialNo) {
		this.rtrxSerialNo = rtrxSerialNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REFUND_TIME", nullable = false, length = 11)
	public Date getRefundTime() {
		return this.refundTime;
	}

	public void setRefundTime(Date refundTime) {
		this.refundTime = refundTime;
	}

	@Column(name = "OTRX_SERIAL_NO", length = 30)
	public String getOtrxSerialNo() {
		return this.otrxSerialNo;
	}

	public void setOtrxSerialNo(String otrxSerialNo) {
		this.otrxSerialNo = otrxSerialNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OTRX_DATE", nullable = false, length = 11)
	public Date getOtrxDate() {
		return this.otrxDate;
	}

	public void setOtrxDate(Date otrxDate) {
		this.otrxDate = otrxDate;
	}

	@Column(name = "OPAY_CHN_NO", length = 8)
	public String getOpayChnNo() {
		return this.opayChnNo;
	}

	public void setOpayChnNo(String opayChnNo) {
		this.opayChnNo = opayChnNo;
	}

	@Column(name = "OPAY_CHN_NAME", length = 30)
	public String getOpayChnName() {
		return this.opayChnName;
	}

	public void setOpayChnName(String opayChnName) {
		this.opayChnName = opayChnName;
	}

	@Column(name = "OMER_BILL_NO", length = 30)
	public String getOmerBillNo() {
		return this.omerBillNo;
	}

	public void setOmerBillNo(String omerBillNo) {
		this.omerBillNo = omerBillNo;
	}

	@Column(name = "OTRX_AMOUN")
	public BigDecimal getOtrxAmount() {
		return this.otrxAmount;
	}

	public void setOtrxAmount(BigDecimal otrxAmount) {
		this.otrxAmount = otrxAmount;
	}

	@Column(name = "REFUND_AMOUNT")
	public BigDecimal getRefundAmount() {
		return this.refundAmount;
	}

	public void setRefundAmount(BigDecimal refundAmount) {
		this.refundAmount = refundAmount;
	}

	@Column(name = "REFUND_STATUS", length = 2)
	public String getRefundStatus() {
		return this.refundStatus;
	}

	public void setRefundStatus(String refundStatus) {
		this.refundStatus = refundStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_TIME", length = 11)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "MEMO", length = 100)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "CONFIRM_USER", length = 20)
	public String getConfirmUser() {
		return this.confirmUser;
	}

	public void setConfirmUser(String confirmUser) {
		this.confirmUser = confirmUser;
	}

	@Column(name = "CONFIRM_STATUS", length = 2)
	public String getConfirmStatus() {
		return this.confirmStatus;
	}

	public void setConfirmStatus(String confirmStatus) {
		this.confirmStatus = confirmStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CONFIRM_TIME", length = 11)
	public Date getConfirmTime() {
		return this.confirmTime;
	}

	public void setConfirmTime(Date confirmTime) {
		this.confirmTime = confirmTime;
	}

	public String getTrxErrDealType() {
		return trxErrDealType;
	}

	public void setTrxErrDealType(String trxErrDealType) {
		this.trxErrDealType = trxErrDealType;
	}
	

}
