package net.easipay.cbp.model;

import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * UcRole generated by hbm2java
 */
@Entity
public class SacSysDic implements java.io.Serializable {

	private String dicCode;
	private String dicDesc;
	private String dicType;
	private String dicTypeDesc;
	private String parentCode;
	private String memo;
	public String getDicCode() {
		return dicCode;
	}
	public void setDicCode(String dicCode) {
		this.dicCode = dicCode;
	}
	public String getDicDesc() {
		return dicDesc;
	}
	public void setDicDesc(String dicDesc) {
		this.dicDesc = dicDesc;
	}
	public String getDicType() {
		return dicType;
	}
	public void setDicType(String dicType) {
		this.dicType = dicType;
	}
	public String getDicTypeDesc() {
		return dicTypeDesc;
	}
	public void setDicTypeDesc(String dicTypeDesc) {
		this.dicTypeDesc = dicTypeDesc;
	}
	public String getParentCode() {
		return parentCode;
	}
	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}
	public String getMemo() {
		return memo;
	}
	public void setMemo(String memo) {
		this.memo = memo;
	}
	
	
	
	  
	  
	
   
	
}
