package net.easipay.cbp.model;

// Generated 2015-7-6 15:57:25 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * SacOtrxInfo generated by hbm2java
 */
@Entity
@Table(name = "SAC_OTRX_INFO", schema = "SAC_SYN")
public class SacOtrxInfo implements java.io.Serializable {

  /**
	 * 
	 */
  private static final long serialVersionUID = -2922429917705296479L;
  private Long id;
  private String custBillNo;
  private String platBillNo;
  private String trxSerialNo;
  private String otrxSerialNo;
  private String etrxSerialNo;
  private String trxState;

  private String craccCusCode;
  private String craccCusType;
  private String craccNo;
  private String craccName;
  private String craccNodeCode;
  private String craccBankName;

  private String draccCusCode;
  private String draccCusType;
  private String draccNo;
  private String draccName;
  private String draccNodeCode;
  private String draccBankName;

  private String payCurrency;
  private BigDecimal exRate;
  private BigDecimal payAmount;
  private String sacCurrency;
  private BigDecimal sacAmount;
  private String bussType;
  private String trxType;
  private String payconType;
  private String payWay;
  private String sacFlag;
  private String innConFlag;
  private String innConStatus;
  private String chaConFlag;
  private String chaConStatus;
  private String memo;
  private String trxBatchNo;
  private Date updateTime;
  private Date createTime;
  private String trxErrDealType;
  private String craccCusName;
  private String draccCusName;
  private BigDecimal taxAmount;
  private BigDecimal transportExpenses;
  private String accountStatus;
  private String reversalStatus;

  private Date trxTime;
  private BigDecimal channelCost;
  private BigDecimal cusCharge;
  private Date trxSuccTime;

  private Long recDiffId;
  private String isSend;

  public SacOtrxInfo() {
  }

  @Id
  @Column(name = "ID", unique = true, nullable = false, scale = 0)
  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  @Column(name = "PLAT_BILL_NO", nullable = false, length = 30)
  public String getplatBillNo() {
    return this.platBillNo;
  }

  public void setplatBillNo(String platBillNo) {
    this.platBillNo = platBillNo;
  }

  @Column(name = "CUS_BILL_NO", nullable = false, length = 30)
  public String getCustBillNo() {
    return custBillNo;
  }

  public void setCustBillNo(String custBillNo) {
    this.custBillNo = custBillNo;
  }

  @Column(name = "TRX_SERIAL_NO", nullable = false, length = 30)
  public String getTrxSerialNo() {
    return this.trxSerialNo;
  }

  public void setTrxSerialNo(String trxSerialNo) {
    this.trxSerialNo = trxSerialNo;
  }

  @Column(name = "OTRX_SERIAL_NO", nullable = false, length = 30)
  public String getOtrxSerialNo() {
    return this.otrxSerialNo;
  }

  public void setOtrxSerialNo(String otrxSerialNo) {
    this.otrxSerialNo = otrxSerialNo;
  }

  @Column(name = "ETRX_SERIAL_NO", nullable = false, length = 30)
  public String getEtrxSerialNo() {
    return this.etrxSerialNo;
  }

  public void setEtrxSerialNo(String etrxSerialNo) {
    this.etrxSerialNo = etrxSerialNo;
  }

  @Column(name = "TRX_STATE", nullable = false, length = 4)
  public String getTrxState() {
    return this.trxState;
  }

  public void setTrxState(String trxState) {
    this.trxState = trxState;
  }

  @Column(name = "CRACC_CUS_CODE", nullable = false, length = 20)
  public String getCraccCusCode() {
    return this.craccCusCode;
  }

  public void setCraccCusCode(String craccCusCode) {
    this.craccCusCode = craccCusCode;
  }

  @Column(name = "CRACC_CUS_TYPE", nullable = false, length = 1)
  public String getCraccCusType() {
    return this.craccCusType;
  }

  public void setCraccCusType(String craccCusType) {
    this.craccCusType = craccCusType;
  }

  @Column(name = "CRACC_NO", nullable = false, length = 50)
  public String getCraccNo() {
    return this.craccNo;
  }

  public void setCraccNo(String craccNo) {
    this.craccNo = craccNo;
  }

  @Column(name = "CRACC_NAME", nullable = false, length = 100)
  public String getCraccName() {
    return this.craccName;
  }

  public void setCraccName(String craccName) {
    this.craccName = craccName;
  }

  @Column(name = "CRACC_NODE_CODE", nullable = false, length = 8)
  public String getCraccNodeCode() {
    return this.craccNodeCode;
  }

  public void setCraccNodeCode(String craccNodeCode) {
    this.craccNodeCode = craccNodeCode;
  }

  @Column(name = "CRACC_BANK_NAME", length = 50)
  public String getCraccBankName() {
    return this.craccBankName;
  }

  public void setCraccBankName(String craccBankName) {
    this.craccBankName = craccBankName;
  }

  @Column(name = "DRACC_CUS_CODE", nullable = false, length = 20)
  public String getDraccCusCode() {
    return this.draccCusCode;
  }

  public void setDraccCusCode(String draccCusCode) {
    this.draccCusCode = draccCusCode;
  }

  @Column(name = "DRACC_CUS_TYPE", length = 1)
  public String getDraccCusType() {
    return this.draccCusType;
  }

  public void setDraccCusType(String draccCusType) {
    this.draccCusType = draccCusType;
  }

  @Column(name = "DRACC_NO", length = 50)
  public String getDraccNo() {
    return this.draccNo;
  }

  public void setDraccNo(String draccNo) {
    this.draccNo = draccNo;
  }

  @Column(name = "DRACC_NAME", length = 100)
  public String getDraccName() {
    return this.draccName;
  }

  public void setDraccName(String draccName) {
    this.draccName = draccName;
  }

  @Column(name = "DRACC_NODE_CODE", nullable = false, length = 8)
  public String getDraccNodeCode() {
    return this.draccNodeCode;
  }

  public void setDraccNodeCode(String draccNodeCode) {
    this.draccNodeCode = draccNodeCode;
  }

  @Column(name = "DRACC_BANK_NAME", nullable = false, length = 40)
  public String getDraccBankName() {
    return this.draccBankName;
  }

  public void setDraccBankName(String draccBankName) {
    this.draccBankName = draccBankName;
  }

  @Column(name = "PAY_CURRENCY", length = 4)
  public String getPayCurrency() {
    return this.payCurrency;
  }

  public void setPayCurrency(String payCurrency) {
    this.payCurrency = payCurrency;
  }

  @Column(name = "PAY_AMOUNT")
  public BigDecimal getPayAmount() {
    return this.payAmount;
  }

  public void setPayAmount(BigDecimal payAmount) {
    this.payAmount = payAmount;
  }

  @Column(name = "BUSS_TYPE", length = 4)
  public String getBussType() {
    return this.bussType;
  }

  public void setBussType(String bussType) {
    this.bussType = bussType;
  }

  @Column(name = "TRX_TYPE", length = 4)
  public String getTrxType() {
    return this.trxType;
  }

  public void setTrxType(String trxType) {
    this.trxType = trxType;
  }

  @Column(name = "PAY_WAY", length = 4)
  public String getPayWay() {
    return this.payWay;
  }

  public void setPayWay(String payWay) {
    this.payWay = payWay;
  }

  @Column(name = "SAC_FLAG", length = 1)
  public String getSacFlag() {
    return this.sacFlag;
  }

  public void setSacFlag(String sacFlag) {
    this.sacFlag = sacFlag;
  }

  @Column(name = "INN_CON_FLAG", length = 1)
  public String getInnConFlag() {
    return this.innConFlag;
  }

  public void setInnConFlag(String innConFlag) {
    this.innConFlag = innConFlag;
  }

  @Column(name = "INN_CON_STATUS", length = 1)
  public String getInnConStatus() {
    return this.innConStatus;
  }

  public void setInnConStatus(String innConStatus) {
    this.innConStatus = innConStatus;
  }

  @Column(name = "PAYCON_TYPE", length = 4)
  public String getPayconType() {
    return this.payconType;
  }

  public void setPayconType(String payconType) {
    this.payconType = payconType;
  }

  @Column(name = "CHA_CON_FLAG", length = 1)
  public String getChaConFlag() {
    return this.chaConFlag;
  }

  public void setChaConFlag(String chaConFlag) {
    this.chaConFlag = chaConFlag;
  }

  @Column(name = "CHA_CON_STATUS", length = 1)
  public String getChaConStatus() {
    return this.chaConStatus;
  }

  public void setChaConStatus(String chaConStatus) {
    this.chaConStatus = chaConStatus;
  }

  @Column(name = "TRX_BATCH_NO", length = 30)
  public String getTrxBatchNo() {
    return this.trxBatchNo;
  }

  public void setTrxBatchNo(String trxBatchNo) {
    this.trxBatchNo = trxBatchNo;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_TIME", length = 11)
  public Date getUpdateTime() {
    return this.updateTime;
  }

  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_TIME", length = 11)
  public Date getCreateTime() {
    return this.createTime;
  }

  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  @Column(name = "TRX_ERR_DEAL_TYPE", length = 2)
  public String getTrxErrDealType() {
    return this.trxErrDealType;
  }

  public void setTrxErrDealType(String trxErrDealType) {
    this.trxErrDealType = trxErrDealType;
  }

  @Column(name = "PLAT_BILL_NO")
  public String getPlatBillNo() {
    return platBillNo;
  }

  public void setPlatBillNo(String platBillNo) {
    this.platBillNo = platBillNo;
  }

  @Column(name = "EX_RATE")
  public BigDecimal getExRate() {
    return exRate;
  }

  public void setExRate(BigDecimal exRate) {
    this.exRate = exRate;
  }

  @Column(name = "SAC_CURRENCY")
  public String getSacCurrency() {
    return sacCurrency;
  }

  public void setSacCurrency(String sacCurrency) {
    this.sacCurrency = sacCurrency;
  }

  @Column(name = "SAC_AMOUNT")
  public BigDecimal getSacAmount() {
    return sacAmount;
  }

  public void setSacAmount(BigDecimal sacAmount) {
    this.sacAmount = sacAmount;
  }

  @Column(name = "MEMO")
  public String getMemo() {
    return memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  @Column(name = "CRACC_CUS_NAME")
  public String getCraccCusName() {
    return craccCusName;
  }

  public void setCraccCusName(String craccCusName) {
    this.craccCusName = craccCusName;
  }

  @Column(name = "DRACC_CUS_NAME")
  public String getDraccCusName() {
    return draccCusName;
  }

  public void setDraccCusName(String draccCusName) {
    this.draccCusName = draccCusName;
  }

  @Column(name = "TAX_AMOUNT")
  public BigDecimal getTaxAmount() {
    return taxAmount;
  }

  public void setTaxAmount(BigDecimal taxAmount) {
    this.taxAmount = taxAmount;
  }

  @Column(name = "TRANSPORT_EXPENSES")
  public BigDecimal getTransportExpenses() {
    return transportExpenses;
  }

  public void setTransportExpenses(BigDecimal transportExpenses) {
    this.transportExpenses = transportExpenses;
  }

  @Column(name = "ACCOUNT_STATUS")
  public String getAccountStatus() {
    return accountStatus;
  }

  public void setAccountStatus(String accountStatus) {
    this.accountStatus = accountStatus;
  }

  @Column(name = "REVERSAL_STATUS")
  public String getReversalStatus() {
    return reversalStatus;
  }

  public void setReversalStatus(String reversalStatus) {
    this.reversalStatus = reversalStatus;
  }

  @Column(name = "TRX_TIME")
  public Date getTrxTime() {
    return trxTime;
  }

  public void setTrxTime(Date trxTime) {
    this.trxTime = trxTime;
  }

  @Transient
  public Long getRecDiffId() {
    return recDiffId;
  }

  public void setRecDiffId(Long recDiffId) {
    this.recDiffId = recDiffId;
  }

  @Column(name = "CHANNEL_COST")
  public BigDecimal getChannelCost() {
    return channelCost;
  }

  public void setChannelCost(BigDecimal channelCost) {
    this.channelCost = channelCost;
  }

  @Column(name = "CUS_CHARGE")
  public BigDecimal getCusCharge() {
    return cusCharge;
  }

  public void setCusCharge(BigDecimal cusCharge) {
    this.cusCharge = cusCharge;
  }

  @Column(name = "TRX_SUCC_TIME")
  public Date getTrxSuccTime() {
    return trxSuccTime;
  }

  public void setTrxSuccTime(Date trxSuccTime) {
    this.trxSuccTime = trxSuccTime;
  }

  @Column(name = "IS_SEND")
  public String getIsSend() {
    return isSend;
  }

  public void setIsSend(String isSend) {
    this.isSend = isSend;
  }

}
