package net.easipay.cbp.model;

// Generated 2015-7-6 15:57:25 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SacRecBatch generated by hbm2java
 */
@Entity
@Table(name = "SAC_REC_BATCH", schema = "SAC_SYN")
public class SacRecBatch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4487162789590851542L;
	private Long recBatchId;
	private String recType;
	private Date recStartDate;
	private Date recEndDate;
	private String recOper;
	private Long recCount;
	private String recStatus;
	private String chnCode;
	private String payconType;
	private Date updateTime;
	private Date createTime;
	private String memo;
	private String recUnionId;

	public SacRecBatch() {
	}

	public SacRecBatch(Long recBatchId) {
		this.recBatchId = recBatchId;
	}

	public SacRecBatch(Long recBatchId, String recType, Date recStartDate,
			Date recEndDate, String recOper, Long recCount, String recStatus,
			String chnCode, String payconType, Date updateTime,
			Date createTime, String memo) {
		super();
		this.recBatchId = recBatchId;
		this.recType = recType;
		this.recStartDate = recStartDate;
		this.recEndDate = recEndDate;
		this.recOper = recOper;
		this.recCount = recCount;
		this.recStatus = recStatus;
		this.chnCode = chnCode;
		this.payconType = payconType;
		this.updateTime = updateTime;
		this.createTime = createTime;
		this.memo = memo;
	}

	@Id
	@Column(name = "REC_BATCH_ID", unique = true, nullable = false, scale = 0)
	public Long getRecBatchId() {
		return this.recBatchId;
	}

	public void setRecBatchId(Long recBatchId) {
		this.recBatchId = recBatchId;
	}

	@Column(name = "REC_TYPE", length = 4)
	public String getRecType() {
		return this.recType;
	}

	public void setRecType(String recType) {
		this.recType = recType;
	}

	@Column(name = "REC_START_DATE", length = 16)
	public Date getRecStartDate() {
		return recStartDate;
	}

	public void setRecStartDate(Date recStartDate) {
		this.recStartDate = recStartDate;
	}

	@Column(name = "REC_END_DATE", length = 16)
	public Date getRecEndDate() {
		return recEndDate;
	}

	public void setRecEndDate(Date recEndDate) {
		this.recEndDate = recEndDate;
	}

	@Column(name = "REC_OPER", length = 16)
	public String getRecOper() {
		return this.recOper;
	}

	public void setRecOper(String recOper) {
		this.recOper = recOper;
	}

	@Column(name = "REC_COUNT", precision = 10, scale = 0)
	public Long getRecCount() {
		return this.recCount;
	}

	public void setRecCount(Long recCount) {
		this.recCount = recCount;
	}

	@Column(name = "REC_STATUS", length = 4)
	public String getRecStatus() {
		return this.recStatus;
	}

	public void setRecStatus(String recStatus) {
		this.recStatus = recStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 11)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 11)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "MEMO", length = 100)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "CHN_CODE")
	public String getChnCode() {
		return chnCode;
	}

	public void setChnCode(String chnCode) {
		this.chnCode = chnCode;
	}

	@Column(name = "PAYCON_TYPE", length = 4)
	public String getPayconType() {
		return this.payconType;
	}

	public void setPayconType(String payconType) {
		this.payconType = payconType;
	}

	@Column(name = "REC_UNION_ID", length = 128)
	public String getRecUnionId() {
		return recUnionId;
	}

	public void setRecUnionId(String recUnionId) {
		this.recUnionId = recUnionId;
	}

}
