package net.easipay.cbp.model;

// Generated 2015-7-6 15:57:25 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SacRecDetail generated by hbm2java
 */
@Entity
@Table(name = "SAC_REC_DETAIL", schema = "SAC_SYN")
public class SacRecDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8500903038205043404L;
	private Long id;
	private Long recBatchId;
	private Date recStartDate;
	private Date recEndDate;
	private String diffType;
	private String trxSerialNo;
	private Date trxTime;
	private BigDecimal payAmount;
	private String currencyType;
	private String bankSerialNo;
	private String chnCode;
	private String payconType;
	private String recOper;
	private String memo;
	private String busiType;

	private String trxCode;
	private String privDomain;

	public SacRecDetail() {
	}

	public SacRecDetail(Long id, Long recBatchId, Date recStartDate,
			Date recEndDate, String diffType, String trxSerialNo, Date trxTime,
			BigDecimal payAmount, String currencyType, String bankSerialNo,
			String chnCode, String payconType, String recOper, String memo,
			String busiType) {
		super();
		this.id = id;
		this.recBatchId = recBatchId;
		this.recStartDate = recStartDate;
		this.recEndDate = recEndDate;
		this.diffType = diffType;
		this.trxSerialNo = trxSerialNo;
		this.trxTime = trxTime;
		this.payAmount = payAmount;
		this.currencyType = currencyType;
		this.bankSerialNo = bankSerialNo;
		this.chnCode = chnCode;
		this.payconType = payconType;
		this.recOper = recOper;
		this.memo = memo;
		this.busiType = busiType;
	}

	@Column(name = "REC_START_DATE", length = 16)
	public Date getRecStartDate() {
		return recStartDate;
	}

	public void setRecStartDate(Date recStartDate) {
		this.recStartDate = recStartDate;
	}

	@Column(name = "REC_END_DATE", length = 16)
	public Date getRecEndDate() {
		return recEndDate;
	}

	public void setRecEndDate(Date recEndDate) {
		this.recEndDate = recEndDate;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "REC_BATCH_ID", scale = 0)
	public Long getRecBatchId() {
		return this.recBatchId;
	}

	public void setRecBatchId(Long recBatchId) {
		this.recBatchId = recBatchId;
	}

	@Column(name = "TRX_SERIAL_NO", length = 32)
	public String getTrxSerialNo() {
		return this.trxSerialNo;
	}

	public void setTrxSerialNo(String trxSerialNo) {
		this.trxSerialNo = trxSerialNo;
	}

	@Column(name = "CHN_CODE")
	public String getChnCode() {
		return chnCode;
	}

	public void setChnCode(String chnCode) {
		this.chnCode = chnCode;
	}

	@Column(name = "MEMO", length = 100)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRX_TIME", length = 11)
	public Date getTrxTime() {
		return this.trxTime;
	}

	public void setTrxTime(Date trxTime) {
		this.trxTime = trxTime;
	}

	@Column(name = "PAY_AMOUNT")
	public BigDecimal getPayAmount() {
		return this.payAmount;
	}

	public void setPayAmount(BigDecimal payAmount) {
		this.payAmount = payAmount;
	}

	@Column(name = "BANK_SERIAL_NO", length = 32)
	public String getBankSerialNo() {
		return this.bankSerialNo;
	}

	public void setBankSerialNo(String bankSerialNo) {
		this.bankSerialNo = bankSerialNo;
	}

	@Column(name = "PAYCON_TYPE", length = 4)
	public String getPayconType() {
		return this.payconType;
	}

	public void setPayconType(String payconType) {
		this.payconType = payconType;
	}

	@Column(name = "REC_OPER", length = 16)
	public String getRecOper() {
		return this.recOper;
	}

	public void setRecOper(String recOper) {
		this.recOper = recOper;
	}

	@Column(name = "DIFF_TYPE")
	public String getDiffType() {
		return diffType;
	}

	public void setDiffType(String diffType) {
		this.diffType = diffType;
	}

	@Column(name = "CURRENCY_TYPE")
	public String getCurrencyType() {
		return currencyType;
	}

	public void setCurrencyType(String currencyType) {
		this.currencyType = currencyType;
	}

	@Column(name = "BUSI_TYPE")
	public String getBusiType() {
		return busiType;
	}

	public void setBusiType(String busiType) {
		this.busiType = busiType;
	}

	@Column(name = "TRX_CODE")
	public String getTrxCode() {
		return trxCode;
	}

	public void setTrxCode(String trxCode) {
		this.trxCode = trxCode;
	}

	@Column(name = "PRIV_DOMAIN")
	public String getPrivDomain() {
		return privDomain;
	}

	public void setPrivDomain(String privDomain) {
		this.privDomain = privDomain;
	}

}
