package net.easipay.cbp.model;

// Generated 2015-7-6 15:57:25 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SacTrxDetail generated by hbm2java
 */
@Entity
@Table(name = "SAC_TRX_DETAIL", schema = "SAC_SYN")
public class SacTrxDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4379686424868310191L;
	private Long id;
	private String chnNo;
	private String cusBillNo;
	private String platBillNo;
	private String trxBatchNo;
	private String trxSerialNo;
	private String otrxSerialNo;
	private String receiverPlatAcc;
	private String paymentPlatAcc;
	private String bussType;
	private String trxType;
	private BigDecimal trxAmount;
	private String trxCurrencyType;
	private String sacCurrency;
	private BigDecimal sacAmount;
	private BigDecimal exRate;
	private String issuingBank;
	private String payconType;
	private String payWay;
	private String draccNodeCode;
	private String craccNodeCode;
	private String trxState;
	private String chaConStatus;
	private Date createTime;
	private Date updateTime;
	private String chnBatchNo;
	private String cusBatchNo;
	private String memo;
	private Date trxTime;

	private BigDecimal channelCost;
	private BigDecimal cusCharge;
	private Date trxSuccTime;

	public SacTrxDetail() {
	}

	public SacTrxDetail(Long id, String cusBillNo) {
		this.id = id;
		this.cusBillNo = cusBillNo;
	}

	public SacTrxDetail(Long id, String chnNo, String cusBillNo,
			String platBillNo, String trxBatchNo, String trxSerialNo,
			String otrxSerialNo, String receiverPlatAcc, String paymentPlatAcc,
			String bussType, String trxType, BigDecimal trxAmount,
			String trxCurrencyType, String sacCurrency, BigDecimal sacAmount,
			BigDecimal trxCost, BigDecimal exRate, String issuingBank,
			String payconType, String payWay, String draccNodeCode,
			String craccNodeCode, String trxState, Date createTime,
			Date updateTime, String chnBatchNo, String cusBatchNo, String memo) {
		super();
		this.id = id;
		this.chnNo = chnNo;
		this.cusBillNo = cusBillNo;
		this.platBillNo = platBillNo;
		this.trxBatchNo = trxBatchNo;
		this.trxSerialNo = trxSerialNo;
		this.otrxSerialNo = otrxSerialNo;
		this.receiverPlatAcc = receiverPlatAcc;
		this.paymentPlatAcc = paymentPlatAcc;
		this.bussType = bussType;
		this.trxType = trxType;
		this.trxAmount = trxAmount;
		this.trxCurrencyType = trxCurrencyType;
		this.sacCurrency = sacCurrency;
		this.sacAmount = sacAmount;
		this.exRate = exRate;
		this.issuingBank = issuingBank;
		this.payconType = payconType;
		this.payWay = payWay;
		this.draccNodeCode = draccNodeCode;
		this.craccNodeCode = craccNodeCode;
		this.trxState = trxState;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.chnBatchNo = chnBatchNo;
		this.cusBatchNo = cusBatchNo;
		this.memo = memo;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CHA_CON_STATUS", length = 1)
	public String getChaConStatus() {
		return this.chaConStatus;
	}

	public void setChaConStatus(String chaConStatus) {
		this.chaConStatus = chaConStatus;
	}

	@Column(name = "CUS_BILL_NO", nullable = false, length = 30)
	public String getCusBillNo() {
		return this.cusBillNo;
	}

	public void setCusBillNo(String cusBillNo) {
		this.cusBillNo = cusBillNo;
	}

	@Column(name = "PLAT_BILL_NO", length = 30)
	public String getPlatBillNo() {
		return this.platBillNo;
	}

	public void setPlatBillNo(String platBillNo) {
		this.platBillNo = platBillNo;
	}

	@Column(name = "TRX_BATCH_NO", length = 30)
	public String getTrxBatchNo() {
		return this.trxBatchNo;
	}

	public void setTrxBatchNo(String trxBatchNo) {
		this.trxBatchNo = trxBatchNo;
	}

	@Column(name = "TRX_SERIAL_NO", length = 30)
	public String getTrxSerialNo() {
		return this.trxSerialNo;
	}

	public void setTrxSerialNo(String trxSerialNo) {
		this.trxSerialNo = trxSerialNo;
	}

	@Column(name = "OTRX_SERIAL_NO", length = 30)
	public String getOtrxSerialNo() {
		return this.otrxSerialNo;
	}

	public void setOtrxSerialNo(String otrxSerialNo) {
		this.otrxSerialNo = otrxSerialNo;
	}

	@Column(name = "RECEIVER_PLAT_ACC", length = 30)
	public String getReceiverPlatAcc() {
		return this.receiverPlatAcc;
	}

	public void setReceiverPlatAcc(String receiverPlatAcc) {
		this.receiverPlatAcc = receiverPlatAcc;
	}

	@Column(name = "PAYMENT_PLAT_ACC", length = 30)
	public String getPaymentPlatAcc() {
		return this.paymentPlatAcc;
	}

	public void setPaymentPlatAcc(String paymentPlatAcc) {
		this.paymentPlatAcc = paymentPlatAcc;
	}

	@Column(name = "BUSS_TYPE", length = 8)
	public String getBussType() {
		return bussType;
	}

	public void setBussType(String bussType) {
		this.bussType = bussType;
	}

	@Column(name = "TRX_TYPE", length = 8)
	public String getTrxType() {
		return trxType;
	}

	public void setTrxType(String trxType) {
		this.trxType = trxType;
	}

	@Column(name = "TRX_AMOUNT")
	public BigDecimal getTrxAmount() {
		return this.trxAmount;
	}

	public void setTrxAmount(BigDecimal trxAmount) {
		this.trxAmount = trxAmount;
	}

	@Column(name = "TRX_CURRENCY_TYPE", length = 4)
	public String getTrxCurrencyType() {
		return this.trxCurrencyType;
	}

	public void setTrxCurrencyType(String trxCurrencyType) {
		this.trxCurrencyType = trxCurrencyType;
	}

	@Column(name = "EX_RATE", precision = 13, scale = 8)
	public BigDecimal getExRate() {
		return exRate;
	}

	public void setExRate(BigDecimal exRate) {
		this.exRate = exRate;
	}

	@Column(name = "ISSUING_BANK", length = 50)
	public String getIssuingBank() {
		return this.issuingBank;
	}

	public void setIssuingBank(String issuingBank) {
		this.issuingBank = issuingBank;
	}

	@Column(name = "PAYCON_TYPE", length = 4)
	public String getPayconType() {
		return this.payconType;
	}

	public void setPayconType(String payconType) {
		this.payconType = payconType;
	}

	@Column(name = "PAY_WAY", length = 4)
	public String getPayWay() {
		return this.payWay;
	}

	public void setPayWay(String payWay) {
		this.payWay = payWay;
	}

	@Column(name = "TRX_STATE", length = 4)
	public String getTrxState() {
		return this.trxState;
	}

	public void setTrxState(String trxState) {
		this.trxState = trxState;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 11)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 11)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "CHN_BATCH_NO")
	public String getChnBatchNo() {
		return chnBatchNo;
	}

	public void setChnBatchNo(String chnBatchNo) {
		this.chnBatchNo = chnBatchNo;
	}

	@Column(name = "CUS_BATCH_NO")
	public String getCusBatchNo() {
		return cusBatchNo;
	}

	public void setCusBatchNo(String cusBatchNo) {
		this.cusBatchNo = cusBatchNo;
	}

	@Column(name = "MEMO", length = 100)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "DRACC_NODE_CODE", length = 8)
	public String getDraccNodeCode() {
		return this.draccNodeCode;
	}

	public void setDraccNodeCode(String draccNodeCode) {
		this.draccNodeCode = draccNodeCode;
	}

	@Column(name = "CRACC_NODE_CODE", length = 8)
	public String getCraccNodeCode() {
		return this.craccNodeCode;
	}

	public void setCraccNodeCode(String craccNodeCode) {
		this.craccNodeCode = craccNodeCode;
	}

	@Column(name = "SAC_CURRENCY")
	public String getSacCurrency() {
		return sacCurrency;
	}

	public void setSacCurrency(String sacCurrency) {
		this.sacCurrency = sacCurrency;
	}

	@Column(name = "SAC_AMOUNT")
	public BigDecimal getSacAmount() {
		return sacAmount;
	}

	public void setSacAmount(BigDecimal sacAmount) {
		this.sacAmount = sacAmount;
	}

	@Column(name = "CHN_NO")
	public String getChnNo() {
		return chnNo;
	}

	public void setChnNo(String chnNo) {
		this.chnNo = chnNo;
	}

	@Column(name = "TRX_TIME")
	public Date getTrxTime() {
		return trxTime;
	}

	public void setTrxTime(Date trxTime) {
		this.trxTime = trxTime;
	}

	@Column(name = "CHANNEL_COST")
	public BigDecimal getChannelCost() {
		return channelCost;
	}

	public void setChannelCost(BigDecimal channelCost) {
		this.channelCost = channelCost;
	}

	@Column(name = "CUS_CHARGE")
	public BigDecimal getCusCharge() {
		return cusCharge;
	}

	public void setCusCharge(BigDecimal cusCharge) {
		this.cusCharge = cusCharge;
	}

	@Column(name = "TRX_SUCC_TIME")
	public Date getTrxSuccTime() {
		return trxSuccTime;
	}

	public void setTrxSuccTime(Date trxSuccTime) {
		this.trxSuccTime = trxSuccTime;
	}

}
