package net.easipay.cbp.model;

// Generated 2015-7-2 9:35:55 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FinCode3 generated by hbm2java
 */
@Entity
@Table(name = "FIN_CODE3", schema = "SAC_SYN")
public class FinCode3 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -579168169676198573L;
	private String code3Id;
	private String codeName;

	public FinCode3() {
	}

	public FinCode3(String code3Id) {
		this.code3Id = code3Id;
	}

	public FinCode3(String code3Id, String codeName) {
		this.code3Id = code3Id;
		this.codeName = codeName;
	}

	@Id
	@Column(name = "CODE3_ID", unique = true, nullable = false, length = 19)
	public String getCode3Id() {
		return this.code3Id;
	}

	public void setCode3Id(String code3Id) {
		this.code3Id = code3Id;
	}

	@Column(name = "CODE_NAME", length = 100)
	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

}
