package net.easipay.cbp.model;

// Generated 2015-7-2 9:35:55 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FinCode6 generated by hbm2java
 */
@Entity
@Table(name = "FIN_CODE6", schema = "SAC_SYN")
public class FinCode6 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2163490498305861772L;
	private String code6Id;
	private String codeName;

	public FinCode6() {
	}

	public FinCode6(String code6Id) {
		this.code6Id = code6Id;
	}

	public FinCode6(String code6Id, String codeName) {
		this.code6Id = code6Id;
		this.codeName = codeName;
	}

	@Id
	@Column(name = "CODE6_ID", unique = true, nullable = false, length = 2)
	public String getCode6Id() {
		return this.code6Id;
	}

	public void setCode6Id(String code6Id) {
		this.code6Id = code6Id;
	}

	@Column(name = "CODE_NAME", length = 100)
	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

}
