package net.easipay.cbp.model;

// Generated 2015-7-2 9:35:55 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FinCode generated by hbm2java
 */
@Entity
@Table(name = "FIN_CODE", schema = "SAC_SYN")
public class FinCode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5980868072553666429L;
	private String codeId;
	private String code1Id;
	private String code2Id;
	private String code3Id;
	private String code4Id;
	private String code5Id;
	private String code6Id;

	public FinCode() {
	}

	public FinCode(String codeId) {
		this.codeId = codeId;
	}

	public FinCode(String codeId, String code1Id, String code2Id,
			String code3Id, String code4Id, String code5Id, String code6Id) {
		this.codeId = codeId;
		this.code1Id = code1Id;
		this.code2Id = code2Id;
		this.code3Id = code3Id;
		this.code4Id = code4Id;
		this.code5Id = code5Id;
		this.code6Id = code6Id;
	}

	@Id
	@Column(name = "CODE_ID", unique = true, nullable = false, length = 31)
	public String getCodeId() {
		return this.codeId;
	}

	public void setCodeId(String codeId) {
		this.codeId = codeId;
	}

	@Column(name = "CODE1_ID", length = 4)
	public String getCode1Id() {
		return this.code1Id;
	}

	public void setCode1Id(String code1Id) {
		this.code1Id = code1Id;
	}

	@Column(name = "CODE2_ID", length = 2)
	public String getCode2Id() {
		return this.code2Id;
	}

	public void setCode2Id(String code2Id) {
		this.code2Id = code2Id;
	}

	@Column(name = "CODE3_ID", length = 19)
	public String getCode3Id() {
		return this.code3Id;
	}

	public void setCode3Id(String code3Id) {
		this.code3Id = code3Id;
	}

	@Column(name = "CODE4_ID", length = 2)
	public String getCode4Id() {
		return this.code4Id;
	}

	public void setCode4Id(String code4Id) {
		this.code4Id = code4Id;
	}

	@Column(name = "CODE5_ID", length = 2)
	public String getCode5Id() {
		return this.code5Id;
	}

	public void setCode5Id(String code5Id) {
		this.code5Id = code5Id;
	}

	@Column(name = "CODE6_ID", length = 2)
	public String getCode6Id() {
		return this.code6Id;
	}

	public void setCode6Id(String code6Id) {
		this.code6Id = code6Id;
	}

}
