package net.easipay.cbp.model;

// Generated 2015-7-2 9:35:55 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FinCode2 generated by hbm2java
 */
@Entity
@Table(name = "FIN_CODE2", schema = "SAC_SYN")
public class FinCode2 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4563367482905879381L;
	private String code2Id;
	private String codeName;

	public FinCode2() {
	}

	public FinCode2(String code2Id) {
		this.code2Id = code2Id;
	}

	public FinCode2(String code2Id, String codeName) {
		this.code2Id = code2Id;
		this.codeName = codeName;
	}

	@Id
	@Column(name = "CODE2_ID", unique = true, nullable = false, length = 2)
	public String getCode2Id() {
		return this.code2Id;
	}

	public void setCode2Id(String code2Id) {
		this.code2Id = code2Id;
	}

	@Column(name = "CODE_NAME", length = 100)
	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

}
