package net.easipay.cbp.model;

// Generated 2015-7-2 9:35:55 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FinCode4 generated by hbm2java
 */
@Entity
@Table(name = "FIN_CODE4", schema = "SAC_SYN")
public class FinCode4 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8167595953123854102L;
	private String code4Id;
	private String codeName;

	public FinCode4() {
	}

	public FinCode4(String code4Id) {
		this.code4Id = code4Id;
	}

	public FinCode4(String code4Id, String codeName) {
		this.code4Id = code4Id;
		this.codeName = codeName;
	}

	@Id
	@Column(name = "CODE4_ID", unique = true, nullable = false, length = 2)
	public String getCode4Id() {
		return this.code4Id;
	}

	public void setCode4Id(String code4Id) {
		this.code4Id = code4Id;
	}

	@Column(name = "CODE_NAME", length = 100)
	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

}
