package net.easipay.cbp.model;

// Generated 2015-7-7 16:37:37 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FinCodeRule generated by hbm2java
 */
@Entity
@Table(name = "FIN_CODE_RULE", schema = "SAC_SYN")
public class FinCodeRule implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = 1177102692274123216L;
    private Long id;
    private String code1;
    private String code2;
    private String code3;
    private String code4;
    private String code5;
    private String code6;

    public FinCodeRule()
    {
    }

    public FinCodeRule(Long id)
    {
	this.id = id;
    }

    public FinCodeRule(Long id, String code1, String code2, String code3, String code4, String code5, String code6)
    {
	this.id = id;
	this.code1 = code1;
	this.code2 = code2;
	this.code3 = code3;
	this.code4 = code4;
	this.code5 = code5;
	this.code6 = code6;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, scale = 0)
    public Long getId()
    {
	return this.id;
    }

    public void setId(Long id)
    {
	this.id = id;
    }

    @Column(name = "CODE1", length = 100)
    public String getCode1()
    {
	return this.code1;
    }

    public void setCode1(String code1)
    {
	this.code1 = code1;
    }

    @Column(name = "CODE2", length = 100)
    public String getCode2()
    {
	return this.code2;
    }

    public void setCode2(String code2)
    {
	this.code2 = code2;
    }

    @Column(name = "CODE3", length = 100)
    public String getCode3()
    {
	return this.code3;
    }

    public void setCode3(String code3)
    {
	this.code3 = code3;
    }

    @Column(name = "CODE4", length = 100)
    public String getCode4()
    {
	return this.code4;
    }

    public void setCode4(String code4)
    {
	this.code4 = code4;
    }

    @Column(name = "CODE5", length = 100)
    public String getCode5()
    {
	return this.code5;
    }

    public void setCode5(String code5)
    {
	this.code5 = code5;
    }

    @Column(name = "CODE6", length = 100)
    public String getCode6()
    {
	return this.code6;
    }

    public void setCode6(String code6)
    {
	this.code6 = code6;
    }

}
