package net.easipay.cbp.model;

// Generated 2015-7-2 9:35:55 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FinCode1 generated by hbm2java
 */
@Entity
@Table(name = "FIN_CODE1", schema = "SAC_SYN")
public class FinCode1 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6046211092780843132L;
	private String code1Id;
	private String codeName;
	private Integer direction;

	public FinCode1() {
	}

	public FinCode1(String code1Id) {
		this.code1Id = code1Id;
	}

	public FinCode1(String code1Id, String codeName, Integer direction) {
		super();
		this.code1Id = code1Id;
		this.codeName = codeName;
		this.direction = direction;
	}

	@Id
	@Column(name = "CODE1_ID", unique = true, nullable = false, length = 4)
	public String getCode1Id() {
		return this.code1Id;
	}

	public void setCode1Id(String code1Id) {
		this.code1Id = code1Id;
	}

	@Column(name = "CODE_NAME", length = 100)
	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	@Column(name = "DIRECTION", length = 1)
	public Integer getDirection() {
		return direction;
	}

	public void setDirection(Integer direction) {
		this.direction = direction;
	}
}
