package net.easipay.cbp.model;

// Generated 2015-7-2 9:35:55 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FinYe generated by hbm2java
 */
@Entity
@Table(name = "FIN_YE", schema = "SAC_SYN")
public class FinYe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8289603659639895567L;
	private String yeId;
	private BigDecimal totalAmount;

	public FinYe() {
	}

	public FinYe(String yeId) {
		this.yeId = yeId;
	}

	public FinYe(String yeId, BigDecimal totalAmount) {
		this.yeId = yeId;
		this.totalAmount = totalAmount;
	}

	@Id
	@Column(name = "YE_ID", unique = true, nullable = false, length = 31)
	public String getYeId() {
		return this.yeId;
	}

	public void setYeId(String yeId) {
		this.yeId = yeId;
	}

	@Column(name = "TOTAL_AMOUNT", precision = 18)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

}
