package net.easipay.cbp.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

/**
 * SacOtrxInfo generated by hbm2java
 */
@Entity
@Table(name = "SAC_OTRX_INFO", schema = "SAC_SYN")
public class SacOtrxInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2922429917705296479L;
	private Long id;
	private String cusBillNo;
	private String platBillNo;
	private String trxSerialNo;
	private String otrxSerialNo;
	private String etrxSerialNo;
	private String trxState;
	private String craccCusCode;
	private String craccCusType;
	//private String craccIdentifyType;
    //@NotBlank(message = "收款方证件号码不能为空")
	//private String craccIdentifyCode;
    @NotBlank(message = "收款方帐号不能为空")
	private String craccNo;
	private String craccName;
	private String craccNodeCode;
	private String craccBankName;
	private String draccCusCode;
	private String draccCusType;
	//private String draccIdentifyType;
    //@NotBlank(message = "付款方证件号码不能为空")
	//private String draccIdentifyCode;
    @NotBlank(message = "付款方帐号不能为空")
	private String draccNo;
	private String draccName;
	private String draccNodeCode;
	private String draccBankName;
	private String payCurrency;
    @NotNull(message = "支付金额不能为空")
    @DecimalMin(value = "0.00", message = "支付金额非法")
	private BigDecimal payAmount;
	private Date updateTime;
	private Date createTime;
	private String bussType;
	private String trxType;
	private String payconType;
	private String payWay;
	private String sacFlag;
	private String innConFlag;
	private String innConStatus;
	private String chaConFlag;
	private String chaConStatus;
	private String trxBatchNo;
	private String memo;
	private String trxErrDealType;
	private BigDecimal exRate;
	private String sacCurrency;
	private BigDecimal sacAmount;
	private String craccCusName;
	private String draccCusName;
	private String confirmUser;
	private String confirmStatus;
	private Date confirmTime;

	public SacOtrxInfo() {
	}

	public SacOtrxInfo(Long id, String cusBillNo, String platBillNo,
			String trxSerialNo, String otrxSerialNo, String etrxSerialNo,
			String trxState, String craccCusCode, String craccCusType,
			String craccIdentifyType, String craccIdentifyCode, String craccNo,
			String craccName, String craccNodeCode, String draccCusCode,
			String draccIdentifyType, String draccIdentifyCode,
			String draccNodeCode, String draccBankName) {
		this.id = id;
		this.cusBillNo = cusBillNo;
		this.platBillNo = platBillNo;
		this.trxSerialNo = trxSerialNo;
		this.otrxSerialNo = otrxSerialNo;
		this.etrxSerialNo = etrxSerialNo;
		this.trxState = trxState;
		this.craccCusCode = craccCusCode;
		this.craccCusType = craccCusType;
		//this.craccIdentifyType = craccIdentifyType;
		//this.craccIdentifyCode = craccIdentifyCode;
		this.craccNo = craccNo;
		this.craccName = craccName;
		this.craccNodeCode = craccNodeCode;
		this.draccCusCode = draccCusCode;
		//this.draccIdentifyType = draccIdentifyType;
		//this.draccIdentifyCode = draccIdentifyCode;
		this.draccNodeCode = draccNodeCode;
		this.draccBankName = draccBankName;
	}

	public SacOtrxInfo(Long id, String cusBillNo, String platBillNo,
			String trxSerialNo, String otrxSerialNo, String etrxSerialNo,
			String trxState, String craccCusCode, String craccCusType,
			String craccIdentifyType, String craccIdentifyCode, String craccNo,
			String craccName, String craccNodeCode, String craccBankName,
			String draccCusCode, String draccCusType, String draccIdentifyType,
			String draccIdentifyCode, String draccNo, String draccName,
			String draccNodeCode, String draccBankName, String payCurrency,
			BigDecimal payAmount, String bussType, String trxType,
			String payWay, String sacFlag, String innConFlag,
			String innConStatus, String payconType, String chaConFlag,
			String chaConStatus, String trxBatchNo, Date updateTime,
			Date createTime, String memo, String trxErrDealType,BigDecimal exRate) {
		this.id = id;
		this.cusBillNo = cusBillNo;
		this.platBillNo = platBillNo;
		this.trxSerialNo = trxSerialNo;
		this.otrxSerialNo = otrxSerialNo;
		this.etrxSerialNo = etrxSerialNo;
		this.trxState = trxState;
		this.craccCusCode = craccCusCode;
		this.craccCusType = craccCusType;
		//this.craccIdentifyType = craccIdentifyType;
		//this.craccIdentifyCode = craccIdentifyCode;
		this.craccNo = craccNo;
		this.craccName = craccName;
		this.craccNodeCode = craccNodeCode;
		this.craccBankName = craccBankName;
		this.draccCusCode = draccCusCode;
		this.draccCusType = draccCusType;
		//this.draccIdentifyType = draccIdentifyType;
		//this.draccIdentifyCode = draccIdentifyCode;
		this.draccNo = draccNo;
		this.draccName = draccName;
		this.draccNodeCode = draccNodeCode;
		this.draccBankName = draccBankName;
		this.payCurrency = payCurrency;
		this.payAmount = payAmount;
		this.bussType = bussType;
		this.trxType = trxType;
		this.payWay = payWay;
		this.sacFlag = sacFlag;
		this.innConFlag = innConFlag;
		this.innConStatus = innConStatus;
		this.payconType = payconType;
		this.chaConFlag = chaConFlag;
		this.chaConStatus = chaConStatus;
		this.trxBatchNo = trxBatchNo;
		this.updateTime = updateTime;
		this.createTime = createTime;
		this.memo = memo;
		this.trxErrDealType = trxErrDealType;
		this.exRate = exRate;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CUS_BILL_NO", nullable = false, length = 30)
	public String getCusBillNo() {
		return this.cusBillNo;
	}

	public void setCusBillNo(String cusBillNo) {
		this.cusBillNo = cusBillNo;
	}

	@Column(name = "PLAT_BILL_NO", nullable = false, length = 30)
	public String getPlatBillNo() {
		return this.platBillNo;
	}

	public void setPlatBillNo(String platBillNo) {
		this.platBillNo = platBillNo;
	}

	@Column(name = "TRX_SERIAL_NO", nullable = false, length = 30)
	public String getTrxSerialNo() {
		return this.trxSerialNo;
	}

	public void setTrxSerialNo(String trxSerialNo) {
		this.trxSerialNo = trxSerialNo;
	}

	@Column(name = "OTRX_SERIAL_NO", nullable = false, length = 30)
	public String getOtrxSerialNo() {
		return this.otrxSerialNo;
	}

	public void setOtrxSerialNo(String otrxSerialNo) {
		this.otrxSerialNo = otrxSerialNo;
	}

	@Column(name = "ETRX_SERIAL_NO", nullable = false, length = 30)
	public String getEtrxSerialNo() {
		return this.etrxSerialNo;
	}

	public void setEtrxSerialNo(String etrxSerialNo) {
		this.etrxSerialNo = etrxSerialNo;
	}

	@Column(name = "TRX_STATE", nullable = false, length = 4)
	public String getTrxState() {
		return this.trxState;
	}

	public void setTrxState(String trxState) {
		this.trxState = trxState;
	}

	@Column(name = "CRACC_CUS_CODE", nullable = false, length = 20)
	public String getCraccCusCode() {
		return this.craccCusCode;
	}

	public void setCraccCusCode(String craccCusCode) {
		this.craccCusCode = craccCusCode;
	}

	@Column(name = "CRACC_CUS_TYPE", nullable = false, length = 1)
	public String getCraccCusType() {
		return this.craccCusType;
	}

	public void setCraccCusType(String craccCusType) {
		this.craccCusType = craccCusType;
	}

	/*@Column(name = "CRACC_IDENTIFY_TYPE", nullable = false, length = 4)
	public String getCraccIdentifyType() {
		return this.craccIdentifyType;
	}

	public void setCraccIdentifyType(String craccIdentifyType) {
		this.craccIdentifyType = craccIdentifyType;
	}

	@Column(name = "CRACC_IDENTIFY_CODE", nullable = false, length = 30)
	public String getCraccIdentifyCode() {
		return this.craccIdentifyCode;
	}

	public void setCraccIdentifyCode(String craccIdentifyCode) {
		this.craccIdentifyCode = craccIdentifyCode;
	}*/

	@Column(name = "CRACC_NO", nullable = false, length = 50)
	public String getCraccNo() {
		return this.craccNo;
	}

	public void setCraccNo(String craccNo) {
		this.craccNo = craccNo;
	}

	@Column(name = "CRACC_NAME", nullable = false, length = 100)
	public String getCraccName() {
		return this.craccName;
	}

	public void setCraccName(String craccName) {
		this.craccName = craccName;
	}

	@Column(name = "CRACC_NODE_CODE", nullable = false, length = 8)
	public String getCraccNodeCode() {
		return this.craccNodeCode;
	}

	public void setCraccNodeCode(String craccNodeCode) {
		this.craccNodeCode = craccNodeCode;
	}

	@Column(name = "CRACC_BANK_NAME", length = 50)
	public String getCraccBankName() {
		return this.craccBankName;
	}

	public void setCraccBankName(String craccBankName) {
		this.craccBankName = craccBankName;
	}

	@Column(name = "DRACC_CUS_CODE", nullable = false, length = 20)
	public String getDraccCusCode() {
		return this.draccCusCode;
	}

	public void setDraccCusCode(String draccCusCode) {
		this.draccCusCode = draccCusCode;
	}

	@Column(name = "DRACC_CUS_TYPE", length = 1)
	public String getDraccCusType() {
		return this.draccCusType;
	}

	public void setDraccCusType(String draccCusType) {
		this.draccCusType = draccCusType;
	}

	/*@Column(name = "DRACC_IDENTIFY_TYPE", nullable = false, length = 4)
	public String getDraccIdentifyType() {
		return this.draccIdentifyType;
	}

	public void setDraccIdentifyType(String draccIdentifyType) {
		this.draccIdentifyType = draccIdentifyType;
	}

	@Column(name = "DRACC_IDENTIFY_CODE", nullable = false, length = 30)
	public String getDraccIdentifyCode() {
		return this.draccIdentifyCode;
	}

	public void setDraccIdentifyCode(String draccIdentifyCode) {
		this.draccIdentifyCode = draccIdentifyCode;
	}*/

	@Column(name = "DRACC_NO", length = 50)
	public String getDraccNo() {
		return this.draccNo;
	}

	public void setDraccNo(String draccNo) {
		this.draccNo = draccNo;
	}

	@Column(name = "DRACC_NAME", length = 100)
	public String getDraccName() {
		return this.draccName;
	}

	public void setDraccName(String draccName) {
		this.draccName = draccName;
	}

	@Column(name = "DRACC_NODE_CODE", nullable = false, length = 8)
	public String getDraccNodeCode() {
		return this.draccNodeCode;
	}

	public void setDraccNodeCode(String draccNodeCode) {
		this.draccNodeCode = draccNodeCode;
	}

	@Column(name = "DRACC_BANK_NAME", nullable = false, length = 40)
	public String getDraccBankName() {
		return this.draccBankName;
	}

	public void setDraccBankName(String draccBankName) {
		this.draccBankName = draccBankName;
	}

	@Column(name = "PAY_CURRENCY", length = 4)
	public String getPayCurrency() {
		return this.payCurrency;
	}

	public void setPayCurrency(String payCurrency) {
		this.payCurrency = payCurrency;
	}

	@Column(name = "PAY_AMOUNT")
	public BigDecimal getPayAmount() {
		return this.payAmount;
	}

	public void setPayAmount(BigDecimal payAmount) {
		this.payAmount = payAmount;
	}

	@Column(name = "BUSS_TYPE", length = 4)
	public String getBussType() {
		return this.bussType;
	}

	public void setBussType(String bussType) {
		this.bussType = bussType;
	}

	@Column(name = "TRX_TYPE", length = 4)
	public String getTrxType() {
		return this.trxType;
	}

	public void setTrxType(String trxType) {
		this.trxType = trxType;
	}

	@Column(name = "PAY_WAY", length = 4)
	public String getPayWay() {
		return this.payWay;
	}

	public void setPayWay(String payWay) {
		this.payWay = payWay;
	}

	@Column(name = "SAC_FLAG", length = 1)
	public String getSacFlag() {
		return this.sacFlag;
	}

	public void setSacFlag(String sacFlag) {
		this.sacFlag = sacFlag;
	}

	@Column(name = "INN_CON_FLAG", length = 1)
	public String getInnConFlag() {
		return this.innConFlag;
	}

	public void setInnConFlag(String innConFlag) {
		this.innConFlag = innConFlag;
	}

	@Column(name = "INN_CON_STATUS", length = 1)
	public String getInnConStatus() {
		return this.innConStatus;
	}

	public void setInnConStatus(String innConStatus) {
		this.innConStatus = innConStatus;
	}

	@Column(name = "PAYCON_TYPE", length = 4)
	public String getPayconType() {
		return this.payconType;
	}

	public void setPayconType(String payconType) {
		this.payconType = payconType;
	}

	@Column(name = "CHA_CON_FLAG", length = 1)
	public String getChaConFlag() {
		return this.chaConFlag;
	}

	public void setChaConFlag(String chaConFlag) {
		this.chaConFlag = chaConFlag;
	}

	@Column(name = "CHA_CON_STATUS", length = 1)
	public String getChaConStatus() {
		return this.chaConStatus;
	}

	public void setChaConStatus(String chaConStatus) {
		this.chaConStatus = chaConStatus;
	}

	@Column(name = "TRX_BATCH_NO", length = 30)
	public String getTrxBatchNo() {
		return this.trxBatchNo;
	}

	public void setTrxBatchNo(String trxBatchNo) {
		this.trxBatchNo = trxBatchNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 11)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 11)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "MEMO", length = 100)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "TRX_ERR_DEAL_TYPE", length = 2)
	public String getTrxErrDealType() {
		return this.trxErrDealType;
	}

	public void setTrxErrDealType(String trxErrDealType) {
		this.trxErrDealType = trxErrDealType;
	}

	@Column(name = "EX_RATE")
	public BigDecimal getExRate()
	{
		return exRate;
	}

	public void setExRate(BigDecimal exRate)
	{
		this.exRate = exRate;
	}

	public String getSacCurrency()
	{
		return sacCurrency;
	}

	public void setSacCurrency(String sacCurrency)
	{
		this.sacCurrency = sacCurrency;
	}

	public BigDecimal getSacAmount()
	{
		return sacAmount;
	}

	public void setSacAmount(BigDecimal sacAmount)
	{
		this.sacAmount = sacAmount;
	}

	public String getCraccCusName()
	{
		return craccCusName;
	}

	public void setCraccCusName(String craccCusName)
	{
		this.craccCusName = craccCusName;
	}

	public String getDraccCusName()
	{
		return draccCusName;
	}

	public void setDraccCusName(String draccCusName)
	{
		this.draccCusName = draccCusName;
	}

	public String getConfirmUser() {
		return confirmUser;
	}

	public void setConfirmUser(String confirmUser) {
		this.confirmUser = confirmUser;
	}

	public String getConfirmStatus() {
		return confirmStatus;
	}

	public void setConfirmStatus(String confirmStatus) {
		this.confirmStatus = confirmStatus;
	}

	public Date getConfirmTime() {
		return confirmTime;
	}

	public void setConfirmTime(Date confirmTime) {
		this.confirmTime = confirmTime;
	}
	
	
}
